<?xml version="1.0" encoding="utf-8"?>
<Project DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <NativeProbeName Condition="'$(NativeProbeName)'==''">engine_probe</NativeProbeName>
    <IntDir>$(MSBuildProjectDirectory)\..\build\obj\engine-probe\</IntDir>
  </PropertyGroup>
  <Import Project="DictionaryProbe.vcxproj" />
  <ItemGroup>
    <ClCompile Remove="dictionary_probe.cpp" />
    <ClCompile Include="..\native\Engine.cpp" />
    <ClCompile Include="..\native\DynamicText.cpp" />
    <ClCompile Include="..\native\UppercaseText.cpp" />
    <ClCompile Include="..\native\Lexicon.cpp" />
    <ClCompile Include="..\native\Text.cpp" />
    <ClCompile Include="..\native\SelectionKeys.cpp" />
    <ClCompile Include="..\native\Settings.cpp" />
    <ClCompile Include="engine_probe.cpp" />
  </ItemGroup>
</Project>
