<?xml version="1.0" encoding="utf-8"?>
<Project DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup><NativeProbeName Condition="'$(NativeProbeName)'==''">engine_probe</NativeProbeName></PropertyGroup>
  <Import Project="..\msbuild\NativeApp.props" />
  <Import Project="..\msbuild\EngineSources.props" />
  <ItemGroup><ClCompile Include="engine_probe.cpp" /></ItemGroup>
  <Import Project="$(VCTargetsPath)\Microsoft.Cpp.targets" />
</Project>
