<?xml version="1.0" encoding="utf-8"?>
<Project DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup><NativeProbeName>manual_timer_probe</NativeProbeName></PropertyGroup>
  <Import Project="DictionaryProbe.vcxproj" />
  <ItemGroup><ClCompile Remove="dictionary_probe.cpp" /><ClCompile Remove="..\native\Dictionary.cpp" />
    <ClCompile Include="..\native\UppercaseText.cpp" /><ClCompile Include="..\native\Text.cpp" /><ClCompile Include="manual_timer_probe.cpp" />
  </ItemGroup>
</Project>
