<?xml version="1.0" encoding="utf-8"?>
<Project DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup><NativeProbeName>reminder_launch_probe</NativeProbeName></PropertyGroup>
  <Import Project="EngineProbe.vcxproj" />
  <ItemGroup><ClCompile Remove="engine_probe.cpp" /><ClCompile Include="..\native\ConfigStore.cpp" /><ClCompile Include="..\native\SchemaCatalog.cpp" /><ClCompile Include="..\native\ReminderLaunch.cpp" /><ClCompile Include="reminder_launch_probe.cpp" /></ItemGroup>
  <ItemDefinitionGroup><Link><AdditionalDependencies>%(AdditionalDependencies)</AdditionalDependencies></Link></ItemDefinitionGroup>
</Project>
