<?xml version="1.0" encoding="utf-8"?>
<Project DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup><NativeProbeName>ssf_probe</NativeProbeName></PropertyGroup>
  <Import Project="ArchitectureLoadProbe.vcxproj" />
  <ItemGroup>
    <ClCompile Remove="architecture_load_probe.cpp" />
    <ClCompile Include="ssf_probe.cpp" />
    <ClCompile Include="..\native\SsfArchive.cpp" />
    <ClCompile Include="..\native\SsfSkin.cpp" />
    <ClCompile Include="..\native\SsfAnimation.cpp" />
  </ItemGroup>
  <ItemDefinitionGroup>
    <ClCompile><WarningLevel>Level4</WarningLevel><TreatWarningAsError>true</TreatWarningAsError></ClCompile>
  </ItemDefinitionGroup>
</Project>
