// Generated by generate_sentence_auto_commit_oracle.py from frozen original methods.
using System;using System.IO;using System.Linq;using System.Globalization;using System.Text;using System.Text.Json;using System.Collections.Generic;
namespace TigerClaw.Core {
internal sealed class AutoCommitOracle {
 const double SentenceEarlyCommitMinimumShare=.995,SentenceEarlyCommitStrongShare=.99999;
 const int SentenceEarlyCommitMaximumNeutralGap=3;
 int SentenceEarlyCommitRequiredEvidenceCount=3,SentenceEarlyCommitRequiredStrongCount=2,SentenceEarlyCommitMinimumRetainedRawLength=3;
 bool SentenceEarlyCommitCountMergedTailEvidence=true;
 sealed class State {public bool Enabled;public int Retain;public int LexiconVersion=>1;
 public bool GetSentenceAutoCommitEnabled()=>Enabled;public int GetSentenceMinRetainedRawLength()=>Retain;}
 State _state=new State();StringBuilder _sentenceRawBuffer=new StringBuilder();
 bool _sentenceAutoCommitSuspended,_sentenceContinuationAfterAutoCommit;
 int _sentenceResultLexiconVersion=1,_sentenceCommittedRawLength,_sentenceLastAutoCommitRawLength,_sentenceGeneration;
 string _sentenceCommittedText="",_sentenceAutoCommitLastSeenRaw="",_sentenceNeuralAcceptedRaw=null,_sentenceNeuralTopText=null;
 SentenceDecodeResult _sentenceDecodeResult=SentenceDecodeResult.Empty;
 Dictionary<string,SentenceAutoCommitTracker> _sentenceAutoCommitTrackers=new Dictionary<string,SentenceAutoCommitTracker>(StringComparer.Ordinal);
 // Only policy/bookkeeping is tested here. The next fixture replaces decode data.
 SentenceDecodeResult FilterSentenceDecodeResultForCommittedPrefix(SentenceDecodeResult r)=>r;
 void RequestSentenceRerank(int generation,string raw,SentenceCandidate[] candidates){}
private sealed class SentenceAutoCommitTracker
        {
            public string Text { get; set; }
            public int RawLength { get; set; }
            public int EvidenceCount { get; set; }
            public int ConsecutiveStrongCount { get; set; }
            public int NeutralGapCount { get; set; }
            public double LastShare { get; set; }
        }
private string TryAutoCommitSentencePrefix()
        {
            if (!_state.GetSentenceAutoCommitEnabled() || _sentenceAutoCommitSuspended)
            {
                ResetSentenceAutoCommitEvidence();
                return null;
            }

            string fullRaw = _sentenceRawBuffer.ToString();
            string evidenceRaw = _sentenceDecodeResult.RawCode ?? string.Empty;
            bool currentGeneration = string.Equals(evidenceRaw, fullRaw, StringComparison.Ordinal);
            bool immediatelyPreviousGeneration = evidenceRaw.Length + 1 == fullRaw.Length &&
                fullRaw.StartsWith(evidenceRaw, StringComparison.Ordinal);
            if (_sentenceResultLexiconVersion != _state.LexiconVersion ||
                (!currentGeneration && !immediatelyPreviousGeneration))
            {
                ResetSentenceAutoCommitEvidence();
                return null;
            }

            // Use the authoritative decoded raw length. Display segmentation
            // spaces and the already committed prefix must not satisfy this
            // gate, and pending generations never count as evidence.
            if (evidenceRaw.Length <= 4)
            {
                ResetSentenceAutoCommitEvidence();
                return null;
            }

            SentenceEarlyCommitEvidence earlyCommitEvidence =
                _sentenceDecodeResult.EarlyCommitEvidence ?? SentenceEarlyCommitEvidence.Empty;
            if (earlyCommitEvidence.ConfidenceTruncated)
            {
                ResetSentenceAutoCommitEvidence();
                return null;
            }

            if (_sentenceAutoCommitLastSeenRaw.Length > 0 &&
                string.Equals(_sentenceAutoCommitLastSeenRaw, evidenceRaw, StringComparison.Ordinal))
            {
                return TryCommitMatureSentencePrefix(evidenceRaw, currentGeneration);
            }

            bool extendsPreviousGeneration = _sentenceAutoCommitLastSeenRaw.Length == 0 ||
                (evidenceRaw.Length == _sentenceAutoCommitLastSeenRaw.Length + 1 &&
                 evidenceRaw.StartsWith(_sentenceAutoCommitLastSeenRaw, StringComparison.Ordinal));
            if (!extendsPreviousGeneration)
            {
                _sentenceAutoCommitTrackers.Clear();
            }
            _sentenceAutoCommitLastSeenRaw = evidenceRaw;

            SentencePrefixEvidence[] prefixes = earlyCommitEvidence.Prefixes ??
                Array.Empty<SentencePrefixEvidence>();
            string acceptedTop = null;
            if (string.Equals(_sentenceNeuralAcceptedRaw, evidenceRaw, StringComparison.Ordinal))
            {
                acceptedTop = _sentenceNeuralTopText ?? string.Empty;
            }
            SentenceCandidate[] visibleCandidates = _sentenceDecodeResult.Candidates ??
                Array.Empty<SentenceCandidate>();
            if (visibleCandidates.Length > 0 && visibleCandidates[0].SupplementScore > 0.0)
            {
                acceptedTop = visibleCandidates[0].Text ?? string.Empty;
            }

            var qualifying = new Dictionary<string, SentencePrefixEvidence>(StringComparer.Ordinal);
            // Dropped incomplete-tail states still participate in comparison.
            // The release policy also lets their supported closed boundaries
            // count as evidence; the evaluator can restore comparison-only mode.
            bool mergedIncompleteTail = earlyCommitEvidence.MergedIncompleteTail;
            bool comparisonOnly = mergedIncompleteTail &&
                !SentenceEarlyCommitCountMergedTailEvidence;
            foreach (SentencePrefixEvidence prefix in prefixes)
            {
                if (prefix == null || string.IsNullOrEmpty(prefix.Text) ||
                    !prefix.BoundaryClosed ||
                    prefix.Share < SentenceEarlyCommitMinimumShare ||
                    prefix.RawLength <= _sentenceCommittedRawLength ||
                    prefix.Text.Length <= _sentenceCommittedText.Length ||
                    !prefix.Text.StartsWith(_sentenceCommittedText, StringComparison.Ordinal) ||
                    (acceptedTop != null &&
                     !acceptedTop.StartsWith(prefix.Text, StringComparison.Ordinal)))
                {
                    continue;
                }

                if (!mergedIncompleteTail &&
                    !SentencePrefixBelongsToVisible(prefix, visibleCandidates))
                {
                    continue;
                }

                qualifying[BuildSentencePrefixTrackerKey(prefix.Text, prefix.RawLength)] = prefix;
            }

            bool retainWithoutCounting = comparisonOnly ||
                (qualifying.Count == 0 &&
                 (earlyCommitEvidence.NeutralLowConfidence ||
                  earlyCommitEvidence.MergedIncompleteTail));
            if (retainWithoutCounting)
            {
                _sentenceAutoCommitTrackers = RetainSentenceAutoCommitTrackersWithoutCounting(
                    prefixes);
                return TryCommitMatureSentencePrefix(evidenceRaw, currentGeneration);
            }

            var nextTrackers = new Dictionary<string, SentenceAutoCommitTracker>(
                StringComparer.Ordinal);
            foreach (KeyValuePair<string, SentencePrefixEvidence> item in qualifying)
            {
                SentencePrefixEvidence prefix = item.Value;
                if (!_sentenceAutoCommitTrackers.TryGetValue(
                        item.Key, out SentenceAutoCommitTracker tracker))
                {
                    tracker = new SentenceAutoCommitTracker
                    {
                        Text = prefix.Text,
                        RawLength = prefix.RawLength
                    };
                }
                tracker.EvidenceCount = Math.Min(
                    Math.Max(1, SentenceEarlyCommitRequiredEvidenceCount),
                    tracker.EvidenceCount + 1);
                tracker.ConsecutiveStrongCount = prefix.Share >= SentenceEarlyCommitStrongShare
                    ? Math.Min(
                        Math.Max(1, SentenceEarlyCommitRequiredStrongCount),
                        tracker.ConsecutiveStrongCount + 1)
                    : 0;
                tracker.NeutralGapCount = 0;
                tracker.LastShare = prefix.Share;
                nextTrackers[item.Key] = tracker;
            }
            _sentenceAutoCommitTrackers = nextTrackers;
            return TryCommitMatureSentencePrefix(evidenceRaw, currentGeneration);
        }
private Dictionary<string, SentenceAutoCommitTracker> RetainSentenceAutoCommitTrackersWithoutCounting(
            SentencePrefixEvidence[] prefixes)
        {
            var nextTrackers = new Dictionary<string, SentenceAutoCommitTracker>(
                StringComparer.Ordinal);
            foreach (KeyValuePair<string, SentenceAutoCommitTracker> item in _sentenceAutoCommitTrackers)
            {
                SentenceAutoCommitTracker tracker = item.Value;
                if (tracker == null ||
                    SentencePrefixContradicted(tracker, prefixes) ||
                    !SentenceTrackerStillSupported(tracker, prefixes))
                {
                    continue;
                }

                tracker.NeutralGapCount++;
                if (tracker.NeutralGapCount > SentenceEarlyCommitMaximumNeutralGap)
                {
                    continue;
                }

                SentencePrefixEvidence current = FindSentencePrefixEvidence(
                    prefixes,
                    tracker.Text,
                    tracker.RawLength);
                if (current != null)
                {
                    tracker.LastShare = current.Share;
                }

                nextTrackers[item.Key] = tracker;
            }

            return nextTrackers;
        }
internal static SentencePrefixEvidence FindSentencePrefixEvidence(
            SentencePrefixEvidence[] prefixes,
            string text,
            int rawLength)
        {
            if (prefixes == null || string.IsNullOrEmpty(text))
            {
                return null;
            }

            foreach (SentencePrefixEvidence prefix in prefixes)
            {
                if (prefix == null ||
                    !string.Equals(prefix.Text, text, StringComparison.Ordinal))
                {
                    continue;
                }

                if (prefix.RawLength == rawLength)
                {
                    return prefix;
                }
            }

            return null;
        }
private static bool SentencePrefixContradicted(
            SentenceAutoCommitTracker tracker,
            SentencePrefixEvidence[] prefixes)
        {
            if (tracker == null || prefixes == null || prefixes.Length == 0)
            {
                return false;
            }

            SentencePrefixEvidence self = FindSentencePrefixEvidence(
                prefixes,
                tracker.Text,
                tracker.RawLength);
            double selfShare = self == null ? 0.0 : self.Share;
            foreach (SentencePrefixEvidence prefix in prefixes)
            {
                if (prefix == null ||
                    string.IsNullOrEmpty(prefix.Text) ||
                    string.Equals(prefix.Text, tracker.Text, StringComparison.Ordinal) ||
                    SentencePrefixExtends(prefix.Text, tracker.Text))
                {
                    continue;
                }

                string sharedStem = CommonOrdinalPrefix(prefix.Text, tracker.Text);
                if (string.IsNullOrEmpty(sharedStem) ||
                    sharedStem.Length >= tracker.Text.Length)
                {
                    continue;
                }

                if (self == null || prefix.Share > selfShare)
                {
                    return true;
                }
            }

            return false;
        }
private static string CommonOrdinalPrefix(string left, string right)
        {
            if (string.IsNullOrEmpty(left) || string.IsNullOrEmpty(right))
            {
                return string.Empty;
            }

            int limit = Math.Min(left.Length, right.Length);
            int index = 0;
            while (index < limit && left[index] == right[index])
            {
                index++;
            }

            return index == 0 ? string.Empty : left.Substring(0, index);
        }
private static bool SentenceTrackerStillSupported(
            SentenceAutoCommitTracker tracker,
            SentencePrefixEvidence[] prefixes)
        {
            if (tracker == null || string.IsNullOrEmpty(tracker.Text))
            {
                return false;
            }

            // Prefix evidence contains every boundary from the merged pool.
            // Textual prefix agreement alone is insufficient because commit
            // bookkeeping consumes raw code at the tracker's exact boundary.
            return FindSentencePrefixEvidence(
                prefixes,
                tracker.Text,
                tracker.RawLength) != null;
        }
private static bool SentencePrefixExtends(string left, string right)
        {
            return !string.IsNullOrEmpty(left) &&
                !string.IsNullOrEmpty(right) &&
                (left.StartsWith(right, StringComparison.Ordinal) ||
                 right.StartsWith(left, StringComparison.Ordinal));
        }
private static bool SentencePrefixBelongsToVisible(
            SentencePrefixEvidence prefix,
            SentenceCandidate[] visibleCandidates)
        {
            if (prefix == null || visibleCandidates == null ||
                string.IsNullOrEmpty(prefix.Text))
            {
                return false;
            }

            foreach (SentenceCandidate candidate in visibleCandidates)
            {
                if (candidate == null ||
                    string.IsNullOrEmpty(candidate.Text) ||
                    !candidate.Text.StartsWith(prefix.Text, StringComparison.Ordinal))
                {
                    continue;
                }

                SentencePathBoundary boundary = candidate.Boundary;
                while (boundary != null)
                {
                    if (boundary.RawLength == prefix.RawLength &&
                        boundary.TextLength == prefix.Text.Length)
                    {
                        return true;
                    }

                    boundary = boundary.Previous;
                }
            }

            return false;
        }
private string TryCommitMatureSentencePrefix(string evidenceRaw, bool currentGeneration)
        {
            SentenceAutoCommitTracker selected = _sentenceAutoCommitTrackers.Values
                .Where(tracker =>
                    (tracker.EvidenceCount >= SentenceEarlyCommitRequiredEvidenceCount ||
                     tracker.ConsecutiveStrongCount >= SentenceEarlyCommitRequiredStrongCount) &&
                    tracker.RawLength > _sentenceCommittedRawLength &&
                    tracker.RawLength <= evidenceRaw.Length &&
                    evidenceRaw.Length - tracker.RawLength >=
                        GetSentenceAutoCommitRetainRawLength() &&
                    tracker.Text.Length > _sentenceCommittedText.Length &&
                    tracker.Text.StartsWith(_sentenceCommittedText, StringComparison.Ordinal))
                .OrderByDescending(tracker =>
                    new StringInfo(tracker.Text).LengthInTextElements)
                .ThenByDescending(tracker => tracker.LastShare)
                .ThenBy(tracker => tracker.RawLength)
                .FirstOrDefault();
            if (selected == null ||
                evidenceRaw.Length - _sentenceLastAutoCommitRawLength < 3)
            {
                return null;
            }
            string commit = selected.Text.Substring(_sentenceCommittedText.Length);
            if (new StringInfo(commit).LengthInTextElements < 1)
            {
                return null;
            }
            _sentenceCommittedText = selected.Text;
            _sentenceCommittedRawLength = selected.RawLength;
            _sentenceLastAutoCommitRawLength = selected.RawLength;
            // Probabilistic early commit chooses a boundary from complete
            // sentence paths that have already competed in the language
            // model. Keep those paths eligible after committing their common
            // prefix; otherwise a valid non-first single-character segment in
            // the retained suffix disappears on the next decode. The stricter
            // first-rank-only continuation rule is only for empty-code commit,
            // where a standalone whole-input non-first candidate must not turn
            // into an implicit segmented choice.
            _sentenceContinuationAfterAutoCommit = false;
            ResetSentenceAutoCommitEvidence();
            _sentenceDecodeResult = FilterSentenceDecodeResultForCommittedPrefix(_sentenceDecodeResult);
            _sentenceGeneration++;
            if (currentGeneration)
            {
                RequestSentenceRerank(_sentenceGeneration, evidenceRaw, _sentenceDecodeResult.Candidates);
            }
            return commit;
        }
private int GetSentenceAutoCommitRetainRawLength()
        {
            int configured = _state.GetSentenceMinRetainedRawLength();
            return configured > 0
                ? Math.Max(SentenceEarlyCommitMinimumRetainedRawLength, configured)
                : SentenceEarlyCommitMinimumRetainedRawLength;
        }
private static string BuildSentencePrefixTrackerKey(string text, int rawLength)
        {
            return (text ?? string.Empty) + "\u001F" +
                rawLength.ToString(CultureInfo.InvariantCulture);
        }
private void ResetSentenceAutoCommitEvidence()
        {
            _sentenceAutoCommitTrackers.Clear();
            _sentenceAutoCommitLastSeenRaw = string.Empty;
        }
 static string Token(string h)=>h=="-"?"":new string(Enumerable.Range(0,h.Length/4).Select(i=>(char)int.Parse(h.Substring(i*4,4),NumberStyles.HexNumber)).ToArray());
 static string Hex(string s)=>s==null?null:string.Concat(s.Select(c=>((int)c).ToString("x4")));
 public static int Run(string path){CultureInfo.CurrentCulture=CultureInfo.InvariantCulture;
 var a=new AutoCommitOracle();var prefixes=new List<SentencePrefixEvidence>();var candidates=new List<SentenceCandidate>();
 foreach(var line in File.ReadLines(path)){var p=line.Split(' ',StringSplitOptions.RemoveEmptyEntries);if(p.Length==0)continue;
 if(p[0]=="B"){a=new AutoCommitOracle();a.SentenceEarlyCommitRequiredEvidenceCount=int.Parse(p[1]);a.SentenceEarlyCommitRequiredStrongCount=int.Parse(p[2]);a.SentenceEarlyCommitMinimumRetainedRawLength=int.Parse(p[3]);a.SentenceEarlyCommitCountMergedTailEvidence=p[4]=="1";}
 if(p[0]=="S"){prefixes.Clear();candidates.Clear();a._sentenceRawBuffer.Clear().Append(Token(p[1]));a._sentenceDecodeResult=new SentenceDecodeResult{RawCode=Token(p[2]),EarlyCommitEvidence=new SentenceEarlyCommitEvidence{ConfidenceTruncated=p[7]=="1",MergedIncompleteTail=p[8]=="1",NeutralLowConfidence=p[9]=="1"}};
 a._state.Enabled=p[3]=="1";a._sentenceAutoCommitSuspended=p[4]=="1";a._sentenceResultLexiconVersion=p[5]=="1"?1:0;a._state.Retain=int.Parse(p[6]);}
 if(p[0]=="P")prefixes.Add(new SentencePrefixEvidence{Text=Token(p[1]),RawLength=int.Parse(p[2]),Share=double.Parse(p[3]),BoundaryClosed=p[4]=="1"});
 if(p[0]=="C"){var c=new SentenceCandidate{Text=Token(p[1]),SupplementScore=double.Parse(p[2])};foreach(var pair in p.Skip(3)){var b=pair.Split(':');c.Boundary=new SentencePathBoundary{Previous=c.Boundary,RawLength=int.Parse(b[0]),TextLength=int.Parse(b[1])};}candidates.Add(c);}
 if(p[0]=="X"){a._sentenceDecodeResult.Candidates=candidates.ToArray();a._sentenceDecodeResult.EarlyCommitEvidence.Prefixes=prefixes.ToArray();var commit=a.TryAutoCommitSentencePrefix();Console.WriteLine(JsonSerializer.Serialize(new{commit=Hex(commit),text=Hex(a._sentenceCommittedText),raw=a._sentenceCommittedRawLength,last=a._sentenceLastAutoCommitRawLength}));}
 }return 0;}
}}
