<?xml version="1.0" encoding="utf-8"?>
<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="SsfResourceSources.props" />
  <ItemGroup>
    <ClCompile Include="$(MSBuildThisFileDirectory)..\native\tsf\CandidateRendererSkin.cpp"><AdditionalOptions>/utf-8 %(AdditionalOptions)</AdditionalOptions></ClCompile>
  </ItemGroup>
</Project>
