"""Generate native window-region spans from the settings artwork (no bitmap changes)."""
from pathlib import Path
from PIL import Image
import hashlib
ROOT=Path(__file__).resolve().parents[1]
frame=ROOT/'assets/settings/tiger-cream-ornaments.png'
tail=ROOT/'assets/settings/tiger-cream-detached-ornaments.png'
a=Image.open(frame).convert('RGBA');t=Image.open(tail).convert('RGBA')
w,h=a.size;ap=a.load();tp=t.load()
def opaque(x,y):
    lx=(x+.5)*640/w;ly=(y+.5)*480/h
    if 6<=lx<54 and 416<=ly<474:
        tx=min(478,int((lx-6)*479/48));ty=min(569,int((ly-416)*570/58))
        if tp[770+tx,140+ty][3]>=128:return True
    if ly>=380 and lx<100:lx=640-lx
    if lx>=624 and 250<=ly<292:ly-=50
    if ly<56 and 164<=lx<240:lx+=146
    return ap[min(w-1,int(lx*w/640)),min(h-1,int(ly*h/480))][3]>=128
center=[y for y in range(h) if opaque(w//2,y)]
top,bottom=min(center),max(center);rects=[]
for y in range(h):
    if top<=y<=bottom:
        left=0;right=w-1
        while left<w and not opaque(left,y):left+=1
        while right>=left and not opaque(right,y):right-=1
        if left<=right:rects.append((left,y,right+1,y+1))
    else:
        x=0
        while x<w:
            while x<w and not opaque(x,y):x+=1
            left=x
            while x<w and opaque(x,y):x+=1
            if x>left:rects.append((left,y,x,y+1))
header='// Generated by tools/build_settings_contour.py; mirrors SettingsSkin::frame().\n'
header+='// Artwork SHA256: '+hashlib.sha256(frame.read_bytes()+tail.read_bytes()).hexdigest()+'\n'
header+='#pragma once\n#include <cstdint>\nnamespace SettingsContour {\n'
header+=f'inline constexpr int width={w},height={h};\n'
header+='struct Span {std::uint16_t left,top,right,bottom;};\ninline constexpr Span spans[]={\n'
header+=''.join('    {'+','.join(map(str,r))+'},\n' for r in rects)
header+='};\n}\n'
(ROOT/'tools/SettingsContour.h').write_text(header)
print('Generated',len(rects),'contour spans')
