param([string]$Output="$PSScriptRoot\..\native\UnicodeData.inc")
$ErrorActionPreference='Stop'
# Development-only generator. Production binaries do not load ICU.
Add-Type -TypeDefinition @'
using System;
using System.Text;
using System.Runtime.InteropServices;
public static class UnicodeTableGenerator {
 [DllImport("icu.dll")] static extern void u_getUnicodeVersion(byte[] version);
 [DllImport("icu.dll")] static extern int u_toupper(int c);
 [DllImport("icu.dll")] static extern int u_tolower(int c);
 [DllImport("icu.dll")] static extern sbyte u_charType(int c);
 [DllImport("icu.dll")] static extern sbyte u_isalpha(int c);
 [DllImport("icu.dll")] static extern sbyte u_isUWhiteSpace(int c);
 static void Ranges(StringBuilder s,string name,Func<int,bool> predicate) {
  s.AppendLine("inline constexpr Range "+name+"[] = {");
  int start=-1;
  for(int c=0;c<=0x110000;c++) {
   bool present=c<0x110000 && predicate(c);
   if(present && start<0) start=c;
   if(!present && start>=0) {s.Append("{0x"+start.ToString("X")+",0x"+(c-1).ToString("X")+"},\n");start=-1;}
  }
  s.AppendLine("};");
 }
 static void Mapping(StringBuilder s,string name,Func<int,int> map) {
  s.AppendLine("inline constexpr Mapping "+name+"[] = {");
  for(int c=0;c<0x110000;c++) {int v=map(c);if(v!=c)s.Append("{0x"+c.ToString("X")+",0x"+v.ToString("X")+"},\n");}
  s.AppendLine("};");
 }
 public static string Generate() {
  var v=new byte[4];u_getUnicodeVersion(v);
  if(v[0]!=15 || v[1]!=1 || v[2]!=0 || v[3]!=0)throw new Exception("Generator requires Unicode 15.1.0; review behavior before upgrading tables.");
  var s=new StringBuilder("// Generated by tools/generate_unicode_properties.ps1 from Windows ICU Unicode 15.1.0.\n// Development-time snapshot; no runtime ICU dependency. Do not edit manually.\n");
  Mapping(s,"upperMappings",u_toupper);Mapping(s,"lowerMappings",u_tolower);
  Ranges(s,"letterRanges",c=>u_isalpha(c)!=0);
  Ranges(s,"decimalRanges",c=>u_charType(c)==9);
  Ranges(s,"whitespaceRanges",c=>u_isUWhiteSpace(c)!=0);
  return s.ToString().Replace("\r\n","\n");
 }
}
'@
[IO.File]::WriteAllText([IO.Path]::GetFullPath($Output),[UnicodeTableGenerator]::Generate(),[Text.UTF8Encoding]::new($false))
