"""Freeze original rank resource as immutable DLL data (no per-host hash table)."""
from pathlib import Path
import hashlib
root=Path(__file__).resolve().parents[1]
source=root/'tools/SentenceOracle/upstream/TigerClaw.Core/Data/sentence_char_ranks.txt'
ordered=list(dict.fromkeys(s for line in source.read_text(encoding='utf-8-sig').splitlines() if (s:=line.strip()) and not s.startswith('#')))
assert all(len(s)==1 for s in ordered),'Rank resource requires a new multi-scalar representation'
rows=sorted((ord(s),i+1) for i,s in enumerate(ordered))
text='// Generated by tools/generate_sentence_ranks.py; source SHA256 '+hashlib.sha256(source.read_bytes()).hexdigest()+'\n'
text+='''#include "SentenceCharacterRanks.h"
#include <algorithm>
#include <iterator>
namespace tiger {
namespace {
// Scalars and integers require no pointer relocations or heap initialization.
struct Rank {std::uint32_t scalar;int rank;};
constexpr Rank ranks[]={
'''
text+=''.join('{0x%x,%d},\n'%(scalar,rank) for scalar,rank in rows)
text+='''};
}
int sentenceCharacterRank(std::u16string_view text) {
 std::uint32_t scalar=0;
 if(text.size()==1)scalar=text.front();
 else if(text.size()==2 && text[0]>=0xd800 && text[0]<=0xdbff && text[1]>=0xdc00 && text[1]<=0xdfff)
  scalar=0x10000+((text[0]-0xd800)<<10)+(text[1]-0xdc00);
 else return 20001;
 auto it=std::lower_bound(std::begin(ranks),std::end(ranks),scalar,[](const Rank& a,std::uint32_t b){return a.scalar<b;});
 return it!=std::end(ranks) && it->scalar==scalar?it->rank:20001;
}
SentenceLexicon::Characters sentenceTopCharacters(int count) {
 SentenceLexicon::Characters result;
 for(const auto& r:ranks)if(r.rank<=count) {
  std::u16string text;
  if(r.scalar<=0xffff)text+=static_cast<char16_t>(r.scalar);
  else {text+=static_cast<char16_t>(0xd800+((r.scalar-0x10000)>>10));text+=static_cast<char16_t>(0xdc00+((r.scalar-0x10000)&1023));}
  result.insert(std::move(text));
 }
 return result;
}
}
'''
(root/'native/SentenceCharacterRanks.cpp').write_text(text)
print('Generated',len(rows),'rank entries')
