"""Extract unchanged original early-commit methods; stub only UI/rerank effects."""
from pathlib import Path
root=Path(__file__).resolve().parents[1]
s=(root/'tools/SentenceOracle/upstream/TigerClaw.Core/InputMethodEngine.cs').read_text()
def block(signature):
 start=s.index(signature);at=s.index('{',start);n=1;end=at+1
 while n:
  n+=(s[end]=='{')-(s[end]=='}');end+=1
 return s[start:end]
methods=[block(x) for x in ['private sealed class SentenceAutoCommitTracker','private string TryAutoCommitSentencePrefix()',
 'private Dictionary<string, SentenceAutoCommitTracker> RetainSentenceAutoCommitTrackersWithoutCounting',
 'internal static SentencePrefixEvidence FindSentencePrefixEvidence','private static bool SentencePrefixContradicted',
 'private static string CommonOrdinalPrefix','private static bool SentenceTrackerStillSupported','private static bool SentencePrefixExtends',
 'private static bool SentencePrefixBelongsToVisible','private string TryCommitMatureSentencePrefix','private int GetSentenceAutoCommitRetainRawLength',
 'private static string BuildSentencePrefixTrackerKey','private void ResetSentenceAutoCommitEvidence']]
wrapper=r'''// Generated by generate_sentence_auto_commit_oracle.py from frozen original methods.
using System;using System.IO;using System.Linq;using System.Globalization;using System.Text;using System.Text.Json;using System.Collections.Generic;
namespace TigerClaw.Core {
internal sealed class AutoCommitOracle {
 const double SentenceEarlyCommitMinimumShare=.995,SentenceEarlyCommitStrongShare=.99999;
 const int SentenceEarlyCommitMaximumNeutralGap=3;
 int SentenceEarlyCommitRequiredEvidenceCount=3,SentenceEarlyCommitRequiredStrongCount=2,SentenceEarlyCommitMinimumRetainedRawLength=3;
 bool SentenceEarlyCommitCountMergedTailEvidence=true;
 sealed class State {public bool Enabled;public int Retain;public int LexiconVersion=>1;
 public bool GetSentenceAutoCommitEnabled()=>Enabled;public int GetSentenceMinRetainedRawLength()=>Retain;}
 State _state=new State();StringBuilder _sentenceRawBuffer=new StringBuilder();
 bool _sentenceAutoCommitSuspended,_sentenceContinuationAfterAutoCommit;
 int _sentenceResultLexiconVersion=1,_sentenceCommittedRawLength,_sentenceLastAutoCommitRawLength,_sentenceGeneration;
 string _sentenceCommittedText="",_sentenceAutoCommitLastSeenRaw="",_sentenceNeuralAcceptedRaw=null,_sentenceNeuralTopText=null;
 SentenceDecodeResult _sentenceDecodeResult=SentenceDecodeResult.Empty;
 Dictionary<string,SentenceAutoCommitTracker> _sentenceAutoCommitTrackers=new Dictionary<string,SentenceAutoCommitTracker>(StringComparer.Ordinal);
 // Only policy/bookkeeping is tested here. The next fixture replaces decode data.
 SentenceDecodeResult FilterSentenceDecodeResultForCommittedPrefix(SentenceDecodeResult r)=>r;
 void RequestSentenceRerank(int generation,string raw,SentenceCandidate[] candidates){}
'''
wrapper+='\n'.join(methods)+r'''
 static string Token(string h)=>h=="-"?"":new string(Enumerable.Range(0,h.Length/4).Select(i=>(char)int.Parse(h.Substring(i*4,4),NumberStyles.HexNumber)).ToArray());
 static string Hex(string s)=>s==null?null:string.Concat(s.Select(c=>((int)c).ToString("x4")));
 public static int Run(string path){CultureInfo.CurrentCulture=CultureInfo.InvariantCulture;
 var a=new AutoCommitOracle();var prefixes=new List<SentencePrefixEvidence>();var candidates=new List<SentenceCandidate>();
 foreach(var line in File.ReadLines(path)){var p=line.Split(' ',StringSplitOptions.RemoveEmptyEntries);if(p.Length==0)continue;
 if(p[0]=="B"){a=new AutoCommitOracle();a.SentenceEarlyCommitRequiredEvidenceCount=int.Parse(p[1]);a.SentenceEarlyCommitRequiredStrongCount=int.Parse(p[2]);a.SentenceEarlyCommitMinimumRetainedRawLength=int.Parse(p[3]);a.SentenceEarlyCommitCountMergedTailEvidence=p[4]=="1";}
 if(p[0]=="S"){prefixes.Clear();candidates.Clear();a._sentenceRawBuffer.Clear().Append(Token(p[1]));a._sentenceDecodeResult=new SentenceDecodeResult{RawCode=Token(p[2]),EarlyCommitEvidence=new SentenceEarlyCommitEvidence{ConfidenceTruncated=p[7]=="1",MergedIncompleteTail=p[8]=="1",NeutralLowConfidence=p[9]=="1"}};
 a._state.Enabled=p[3]=="1";a._sentenceAutoCommitSuspended=p[4]=="1";a._sentenceResultLexiconVersion=p[5]=="1"?1:0;a._state.Retain=int.Parse(p[6]);}
 if(p[0]=="P")prefixes.Add(new SentencePrefixEvidence{Text=Token(p[1]),RawLength=int.Parse(p[2]),Share=double.Parse(p[3]),BoundaryClosed=p[4]=="1"});
 if(p[0]=="C"){var c=new SentenceCandidate{Text=Token(p[1]),SupplementScore=double.Parse(p[2])};foreach(var pair in p.Skip(3)){var b=pair.Split(':');c.Boundary=new SentencePathBoundary{Previous=c.Boundary,RawLength=int.Parse(b[0]),TextLength=int.Parse(b[1])};}candidates.Add(c);}
 if(p[0]=="X"){a._sentenceDecodeResult.Candidates=candidates.ToArray();a._sentenceDecodeResult.EarlyCommitEvidence.Prefixes=prefixes.ToArray();var commit=a.TryAutoCommitSentencePrefix();Console.WriteLine(JsonSerializer.Serialize(new{commit=Hex(commit),text=Hex(a._sentenceCommittedText),raw=a._sentenceCommittedRawLength,last=a._sentenceLastAutoCommitRawLength}));}
 }return 0;}
}}
'''
(root/'tools/SentenceOracle/AutoCommitOracle.cs').write_text(wrapper)
