<?xml version="1.0" encoding="utf-8"?>
<Project DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup><NativeProbeName>timer_reminder</NativeProbeName></PropertyGroup>
  <Import Project="..\tests\EngineProbe.vcxproj" />
  <ItemGroup><ClCompile Remove="engine_probe.cpp" /><ClCompile Include="..\native\ConfigStore.cpp" /><ClCompile Include="..\native\SchemaCatalog.cpp" /><ClCompile Include="timer_reminder.cpp" /></ItemGroup>
  <ItemDefinitionGroup><Link><AdditionalDependencies>ole32.lib;user32.lib;icu.lib;%(AdditionalDependencies)</AdditionalDependencies></Link></ItemDefinitionGroup>
</Project>
