<?xml version="1.0" encoding="utf-8"?>
<Project DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup><NativeProbeName>schema_manager</NativeProbeName></PropertyGroup>
  <Import Project="..\tests\EngineProbe.vcxproj" />
  <ItemGroup><ClCompile Remove="engine_probe.cpp" />
    <ClCompile Include="..\native\ConfigStore.cpp" /><ClCompile Include="..\native\SchemaCatalog.cpp" />
    <ClCompile Include="schema_manager.cpp" />
    <ClCompile Include="InputSettings.cpp" />
    <ClCompile Include="SelectionSettings.cpp" />
  </ItemGroup>
  <ItemDefinitionGroup><Link><SubSystem>Windows</SubSystem><AdditionalDependencies>comctl32.lib;icu.lib;ole32.lib;shell32.lib;user32.lib;gdi32.lib;uuid.lib;%(AdditionalDependencies)</AdditionalDependencies></Link></ItemDefinitionGroup>
</Project>
