<?xml version="1.0" encoding="utf-8"?>
<Project DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup><NativeProbeName>Tigirl</NativeProbeName></PropertyGroup>
  <Import Project="..\msbuild\NativeApp.props" />
  <Import Project="..\msbuild\EngineSources.props" />
  <ItemGroup>
    <ClCompile Include="..\native\ConfigStore.cpp" /><ClCompile Include="..\native\SchemaCatalog.cpp" />
    <ClCompile Include="schema_manager.cpp" /><ClCompile Include="..\native\UserStore.cpp" />
    <ClCompile Include="InputSettings.cpp" /><ClCompile Include="FontChooser.cpp" />
    <ClCompile Include="..\native\SentenceSettings.cpp" />
    <ClCompile Include="SelectionSettings.cpp" />
  </ItemGroup>
  <ItemDefinitionGroup><Link><SubSystem>Windows</SubSystem><AdditionalDependencies>dwrite.lib;d2d1.lib;comctl32.lib;ole32.lib;shell32.lib;user32.lib;gdi32.lib;uuid.lib;%(AdditionalDependencies)</AdditionalDependencies></Link></ItemDefinitionGroup>
  <ItemGroup><ResourceCompile Include="SchemaManager.rc" /></ItemGroup>
  <Import Project="$(VCTargetsPath)\Microsoft.Cpp.targets" />
</Project>
